Allow admins to see the group reports nav item
discourse/discourse-data-explorer pull request #101
Opened 2021-03-02 14:16 UTC by graydenshand

Previously, the report tab would appear only if the user was a member of the group. With this change, admins can see the reports in any group.

2021-03-15 18:29 UTC, graydenshand commented
Bueller..? Please accept this pull request or let me know what I need to change for it to be accepted.

2021-04-08 13:21 UTC, davidtaylorhq requested changes
Sorry for the delay here @graydenshand - overall the fix looks good, but there is a 'prettier' failure showing in the CI checks. Can you try running prettier against your changes, and commit the result?

2021-04-08 14:50 UTC, davidtaylorhq approved these changes
Looks great, thanks!

2021-04-08 14:50 UTC, merged

2021-04-08 14:51 UTC, graydenshand commented
Thanks for your help with this @davidtaylorhq!